
GET http://localhost:44300/games/1
###
PUT http://localhost:44300/games/1
Content-Type: application/json

{
  "name": "Street Fighters",
  "genre": "Fighting",
  "price": 19.99,
  "releaseDate": "1992-07-15"
}
